name: Build Windows Nightly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter (official)
      uses: flutter-actions/setup-flutter@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows

    - name: Show build output (debug)
      run: dir build\windows\x64\runner\Release

    - name: Create ZIP archive
      run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath comico_windows_nightly.zip

    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: comico_windows_nightly.zip

  release:
    name: Publish Nightly Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-build
        path: .

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        name: Nightly Build
        body: Automated nightly build for Windows.
        draft: false
        prerelease: true
        files: comico_windows_nightly.zip
        token: ${{ secrets.GITHUB_TOKEN }}
